server:
  port: 18001

spring:
  application:
    name: SpringBootDemo01-Provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: hanjunzhe
    password: hanjunzhe
    url: jdbc:mysql://119.29.60.31:3306/dietguide
  redis:
    cluster:
      nodes: 10.12.159.107:7000,10.12.159.107:7001,10.12.159.107:7002,10.12.159.107:8001,10.12.159.107:8002,10.12.159.107:8003
      max-redirects: 6
      command-timeout: 8000
      max-attempts: 5
      max-active: 16
      max-wait: 8000
      max-idle: 8
      min-idle: 0
      test-on-borrow: true
    pool:
      max-active: 16
      max-idle: 8
      max-wait: 8000
      min-idle: 0

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.je1809.pojo

eureka:
  client:
    service-url:
      defaultZone: http://dietguide1.com:7001/eureka/,http://dietguide2.com:7002/eureka/

  instance:
    instance-id: SpringBootDemo01-Provider   #自定义服务实例名称
    prefer-ip-address: true       #访问路径可以显示ip

info:
  app.name: SpringCloudDemo
  compan.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
